### ISSUE TITLE
Custom style for subzones does not work

### ISSUE THREAD

**Issue by byklop** [webbukkit/dynmap-residence#1]
I tried to define custom style for "myresidence.mysubzone" in config.yml, but it didn't work, it shows the subzone, but with regionstyle not being overriden, I defined it like this ():

custstyle:
    myresidence:
        mysubzone:
            strokeColor: "#00FF00"

I also tried:

custstyle:
    myresidence.mysubzone:
            strokeColor: "#00FF00"

But this is automatically converted to my first example. I have this problem only with subzones, not with simple residences. I'm running dynmap-residence v0.14.1 with dynmap v0.29.2 on bukkit v1.0.1-R1.

**Comment by mikeprimm** [comment]
Can you confirm that this is still an issue (0.20)?
