### ISSUE TITLE
Not working in 1.3.1

### ISSUE THREAD

**Issue by ldrrp** [webbukkit/dynmap-residence#4]
25.08 05:54:23 [Server] INFO at org.dynmap.residence.DynmapResidencePlugin$ResidenceUpdate.run(DynmapResidencePlugin.java:107)
25.08 05:54:23 [Server] INFO at org.dynmap.residence.DynmapResidencePlugin.access$000(DynmapResidencePlugin.java:38)
25.08 05:54:23 [Server] INFO at org.dynmap.residence.DynmapResidencePlugin.updateResidence(DynmapResidencePlugin.java:291)
25.08 05:54:23 [Server] INFO at org.dynmap.residence.DynmapResidencePlugin.handleResidence(DynmapResidencePlugin.java:227)
25.08 05:54:23 [Server] INFO at org.dynmap.residence.DynmapResidencePlugin.formatInfoWindow(DynmapResidencePlugin.java:129)
25.08 05:54:23 [Server] INFO at java.lang.String.replace(Unknown Source)
25.08 05:54:23 [Server] INFO java.lang.NullPointerException
25.08 05:54:23 [Server] WARNING Task of 'dynmap-residence' generated an exception

**Comment by mikeprimm** [comment]
Fixed on current releases
