### ISSUE TITLE
Residences not showing after upgrading to Residence v2.6.6.2

### ISSUE THREAD

**Issue by kevmo314** [webbukkit/dynmap-residence#8]
Plugins:
Residence v2.6.6.2
dynmap-residence v0.40
dynmap v1.3-1468

Residences aren't appearing anymore (they were previously, upgraded from Res v2.6.5.2). Configuration, etc unchanged. Any ideas?

**Comment by mikeprimm** [comment]
Updating dev build to 2.6.6.5 now
