### ISSUE TITLE
ResDepth option being ignored

### ISSUE THREAD

**Issue by MacGyverDev** [webbukkit/dynmap-residence#9]
The ResDepth option is ignored causing all residences to be visible on the map.

CB 1.4.7-R1.0 #2624
dynmap 1.4
dynmap-residence 0.40
Residence 2.6.6.3Dev

I'm guessing something broke in the Residence API because this issued didnt appear with a change in dynmap or dynmap-residence.  But has persisted through versions 0.30, 0.40 and 0.50 of dynmap-residence and many versions of dynmap itself.

**Comment by t00thpick1** [comment]
Just put in a PR that should fix that.

**Comment by MacGyverDev** [comment]
Yep that fixed it in the latest 0.50 dev.  Thanks for cleaning up my map.
